### ISSUE TITLE
How to run real-time estimation.

### ISSUE THREAD

**Issue by vsantosu** [fabro66/GAST-Net-3DPoseEstimation#10]
I see there is a amazing update for doing real-time 3D pose estimation. Is there any documentation on how to run this with the pre-trained models?

Thanks for your work by the way!

**Comment by fabro66** [comment]
Hi~  There is some code on detection and tracking that has not been uploaded. Next month I will upload it and post a tutorial on how to achieve real-time 3D pose estimation.  #5

**Comment by vsantosu** [comment]
Thanks so much @fabro66 ! I'm looking forward to see it in action. 

Thanks again for your amazing academic work! :)

**Comment by rirri93** [comment]
I'm really interested in real-time estimation. Any news about the release date?
