### ISSUE TITLE
Unknown person number

### ISSUE THREAD

**Issue by rirri93** [fabro66/GAST-Net-3DPoseEstimation#17]
Hi,
I'd like to use GAST-Net with generic video streams without knowing how many people are in the scene in advance. I need to do this in order to have 3D skeletons of every person depicted in the scene. 
Is it possible? Thanks

**Comment by yerzhan7orazayev** [comment]
@rirri93 Did you get skeleton animation in 3D? 
Have not you encoundtered #16 ? Thanks!

**Comment by fabro66** [comment]
It is possible to reconstruct multi-people 3D poses from a scene.  But the reconstructed accuracy will be subjected to the detected 2D pose. We recommend it for single and two-person scenarios.
