### ISSUE TITLE
Error of pretrained model 

### ISSUE THREAD

**Issue by Vegetebird** [fabro66/GAST-Net-3DPoseEstimation#19]
Hello~
Thanks for your great work, I have some questions:

1. When I run the "python trainval.py  -k cpn_ft_h36m_dbb -arc 3,3,3,3 -c checkpoint/gastnet --evaluate 81_frame_model.bin", I got the error of "size mismatch for layers_graph_conv.3.cat_bn.running_var: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([2048])."

2. What's the performance of single frame as input, and could yout provide the pretrained model of single frame?

**Comment by fabro66** [comment]
Hi~
1. To test the 81 receptive field model, we need to set the channels parameter to 64.
```
python trainval.py -k cpn_ft_h36m_dbb -arc 3,3,3,3 -c checkpoint/gastnet --evaluate 81_frame_model.bin -ch 64
```
2. Single-frame model is worse than video-based models. The performance comparison can be seen in the [video](https://www.youtube.com/watch?v=ojNRPCHufWA&feature=youtu.be) we provide. We do not consider providing the pretrained model of single frame.

**Comment by Vegetebird** [comment]
Hi~Thank you for your reply. 
How can I train the single frame model, just set the "-arc 1"?
And could you provide the performance value of single frame model?

**Comment by fabro66** [comment]
Hi~
You can set the following configurations to train different receptive field models.
1 frame model: **-arc 1,1,1 -ch 128 -drop 0.10**
3 frame model: **-arc 3,1,1 -ch 128 -drop 0.10**
9 frame model: **-arc 3,3 -ch 128** (results in paper)  or  **-arc 3,3,1 -ch 128** (higher precision but increasing computation)
27 frame model: **-arc 3,3,3 -ch 128**
81 frame model: **-arc 3,3,3,3 -ch 64**
243 frame model:  **-arc 3,3,3,3,3 -ch 32 --downsample 1**
