### ISSUE TITLE
How to get the video of demo?

### ISSUE THREAD

**Issue by flyyyyer** [fabro66/GAST-Net-3DPoseEstimation#20]
How can I get the video as your provided as follows? To get the world coordinate and have the trajectory. 

[2020/08/14] We achieve real-time 3D pose estimation. [video]
[2020/10/15] We achieve real-time online 3D skeleton-based action recognition with a single RGB camera. [video]

**Comment by fabro66** [comment]
Hi~
The trajectory in our video is the virtual world coordinates converted from the image coordinates. For the specific conversion method, please refer to #9.

**Comment by flyyyyer** [comment]
So how can I use the "revise_skes_real_time”, what's the value of width should I set?

**Comment by fabro66** [comment]
Hi~
The value of width is of little reference, just for better rendering animation.
