### ISSUE TITLE
Running the code without YOLOv3 and SORT

### ISSUE THREAD

**Issue by yerzhan7orazayev** [fabro66/GAST-Net-3DPoseEstimation#22]
Dear @fabro66,

Is it possible to run the without YOLOv3 and SORT? If so, how one can modify the code?

Thanks.

**Comment by fabro66** [comment]
Hi~
If there is only one person in the video, the YOLOv3 and SORT can be removed. But it will affect the accuracy of 2D poses because HRNet is a top-down method.
