### ISSUE TITLE
pretrained model error

### ISSUE THREAD

**Issue by shenbiren** [fabro66/GAST-Net-3DPoseEstimation#23]
Hello!Thanks for your excellent work. I have some problem in testing with the pretrained model
I downloaded the 81 frame model and use the command:
**python trainval.py -k cpn_ft_h36m_dbb -arc 3,3,3,3 -c checkpoint/gastnet --evaluate 81_frame_model.bin -ch 64**
however I got a error:
Traceback (most recent call last):
  File "trainval.py", line 55, in <module>
    model_pos_train, model_pos, checkpoint = load_weight(args, model_pos_train, model_pos)
  File "/home/leiq1995/25years/GAST-Net-3DPoseEstimation-master/main.py", line 237, in load_weight
    model_pos_train.load_state_dict(new_state_dict)
  File "/root/anaconda3/envs/gast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SpatioTemporalModelOptimized1f:
	Missing key(s) in state_dict: "init_bn.weight", "init_bn.bias", "init_bn.running_mean", "init_bn.running_var", "expand_bn.weight", "expand_bn.bias", "expand_bn.running_mean", "expand_bn.running_var", "shrink.weight", "expand_conv.weight", "layers_conv.0.weight", "layers_conv.1.weight", "layers_conv.2.weight", "layers_conv.3.weight",......

The error information is very long.

When I run the train command, there is no error.

**Comment by fabro66** [comment]
Hi ~
Thank you for your interest in our work. 
I have fixed the bug about evaluation on CPU. Please replace **trainval.py** and **main.py files* to evaluate the pretrained model.
best wishes!
