### ISSUE TITLE
Interpreting the output

### ISSUE THREAD

**Issue by yerzhan7orazayev** [fabro66/GAST-Net-3DPoseEstimation#24]
Hi @fabro66,

I want to understand the output (given by prediction variable in `gen_skes.py`). It is a list of length T (number of frames) where each element being an array of shape (1x17x3). In this regard, what are these numbers? I am assuming that they are x, y, and z coordinates in metric space aligned w.r.t. pelvis joint. In this regard, is the following coordinate system (origin is in pelvis joint) axis correct?

![coordinate system](https://user-images.githubusercontent.com/30374159/100781380-ff7bd900-341b-11eb-9966-c292abc9619a.JPG)

On the other hand, I have seen that you do `prediction[0][:, :, 2] -= np.amin(prediction[0][:, :, 2])` for "adding absolute distance to 3D poses and rebase the height". Could you please explain it in more detail?

**Comment by fabro66** [comment]
Hi~
1. (T, N, C) :   T: Number of frames, N: numbers of joints, C: the (x, y, z) coordinates. Please see our paper for more details.
2. 
![image](https://user-images.githubusercontent.com/43380407/100876600-8eebbf80-34e2-11eb-8660-25ab8fa986bb.png)
3. You comment out this line of code and you will know what it means by comparing the results.
