### ISSUE TITLE
Recommended way to get 2D keypoints

### ISSUE THREAD

**Issue by vsantosu** [fabro66/GAST-Net-3DPoseEstimation#3]
Hello there.

I'm trying to feed some Open Pose COCO keypoints in the same format as the example in the repo. In fact, I'm extracting the COCO 2D points of the baseball video using Open Pose but I get some occluded parts that shows in the x,y coordinates as:

-1, -1

This causes GAST-NET to go crazy when trying to reconstruct the 3D points. Can you provide some insight on the best way to prevent this? Which Model did you used to get the keypoints in the example data?(baseball)

**Comment by fabro66** [comment]
Hi, there.
In my repo, I first use yolo3 and sort to detect and track people. Then I lift 2D poses predicted from HRNet to 3D poses. 
In the future, I will release the code for how to track and estimate multi-person 3D poses from the video in real-time.

**Comment by vsantosu** [comment]
That sounds like an interesting approach, @fabro66 ...

So you combine object detection and a keypoint extraction model. Is this repository you are talking about publicly available? 

I see that you have an OpenPose PyTorch in your repository list, but I cannot find a repo with HRNet+Yolo.

I would like to give it a shot to extract the keypoints of some videos I have.

Thanks again for your help, this is high-quality work!

**Comment by fabro66** [comment]
Hi~  Thank you for your interest in our work.
Recently, I am arranging the whole project of YOLOv3+SORT+HRNet+GAST-Net. Sorry that this project has not been uploaded to my GitHub yet. I will upload it to this project after finishing it.

**Comment by vsantosu** [comment]
Thanks so much @fabro66 , if there is something I can help you with, please let me know.

Thanks for your amazing work!

**Comment by fabro66** [comment]
> Thanks so much @fabro66 , if there is something I can help you with, please let me know.
> 
> Thanks for your amazing work!

Ok. Thanks. If you have any other questions, please feel free to contact me.

**Comment by christw16** [comment]
@vsantosu  
Hi, I use alphapose to generate 2d keypointss json file
But it seems that it does not work for here...
How to fix this problem?
Thank you
