### ISSUE TITLE
Action recognition

### ISSUE THREAD

**Issue by rirri93** [fabro66/GAST-Net-3DPoseEstimation#31]
Hi! 
Do you know any action recognition framework that can work with 3D skeletons generated by GASTNet?

**Comment by fabro66** [comment]
Hi~
Sorry for no prompt reply.  
We have released a skeleton-based action recognition repo, which is compatible with GASTNet. Please check it. 
 [Online-Skeleton-based-Action-Recognition](https://github.com/fabro66/Online-Skeleton-based-Action-Recognition)

**Comment by rirri93** [comment]
Hi! 
thanks, this is really good news.
