### ISSUE TITLE
 I think line 159 of gen_skes.py should be changed.

### ISSUE THREAD

**Issue by wwnis7** [fabro66/GAST-Net-3DPoseEstimation#32]
I think line 159 of gen_skes.py should be changed 
from np.savez_compressed(output_root+output_npz, reconstruction=prediction) to np.savez_compressed(output_npz, reconstruction=prediction).

Thanks for the good code.

**Comment by fabro66** [comment]
Thank you for pointing out the error. We have fixed it.
