### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by vkmavani** [fabro66/GAST-Net-3DPoseEstimation#34]
Thank you...
How to use this for live Pose-Estimation?

**Comment by fabro66** [comment]
Hi~  
We use [pyqtgraph](http://www.pyqtgraph.org/) for live pose estimation. You can implement the real-time pose estimation according to the following demo of pyqtgraph.
<div align=center>
<img src="http://www.pyqtgraph.org/images/pyqtgraph-3d.png" width="480" alt="pyqtgraph demo">
</div>

**Comment by vkmavani** [comment]
Can you provide me source code for that?

**Comment by fabro66** [comment]
Thanks for the interest.
Sorry, we do not plan to release the real-time estimation code.
