### ISSUE TITLE
humaneva dataset train and test error 

### ISSUE THREAD

**Issue by jiajiajun** [fabro66/GAST-Net-3DPoseEstimation#36]
hello, thanks for your great work!
while I train and test the model on humaneva dataset, I've met with the following problem, and the dataset is generated as your guideline of VideoPose3D, and I found and located where the output become 0 (guess it may be the reason), but I don't understand why it happened, could you please help to solve it? Thanks very much!
The error:
Traceback (most recent call last):
  File "/home/PoseEstimation/GAST-Net-3DPoseEstimation-master/main.py", line 338, in evaluate
    epoch_loss_3d_pos_procrustes += inputs_3d.shape[0] * inputs_3d.shape[1] * p_mpjpe(predicted_3d_pos, inputs)
  File "/home/PoseEstimation/GAST-Net-3DPoseEstimation-master/common/loss.py", line 34, in p_mpjpe
    U, s, Vt = np.linalg.svd(H)
  File "/usr/local/python3.6.1/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1612, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/usr/local/python3.6.1/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
The location where input and output become 0:
def relu(input, inplace=False):
    # type: (Tensor, bool) -> Tensor
    r"""relu(input, inplace=False) -> Tensor

    Applies the rectified linear unit function element-wise. See
    :class:`~torch.nn.ReLU` for more details.
    """
    if inplace:
        result = torch.relu_(input) 
%when the forward process passes through the above line, both the input and output suddenly become 0, which are both normal before.

**Comment by fabro66** [comment]
Hi~ 
I just trained and test the model on HumanEva dataset, but I didn't meet the problem. Please check if the training set and test set of HumanEva are ok.
- Train
```
python trainval.py -d humaneva15 -e 200 -k detectron_pt_coco -d humaneva15 -arc 3,3,3 -drop 0.5 -b 32 -lrd 0.98 -str Train/S1,Train/S2,Train/S3 -ste Validate/S1,Validate/S2,Validate/S3 -a Walk,Jog,Box --by-subject
```
- Test
```
python trainval.py -d humaneva15 -e 200 -k detectron_pt_coco -d humaneva15 -arc 3,3,3 -drop 0.5 -b 32 -lrd 0.98 -str Train/S1,Train/S2,Train/S3 -ste Validate/S1,Validate/S2,Validate/S3 -a Walk,Jog,Box --by-subject --evaluate epoch_200.bin
```

**Comment by jiajiajun** [comment]
@fabro66 Thanks for your help! I have reprocessed the data, trained and tested the model, and now there is no problem. Although I do not know the exact cause of the previous problem, it is now working normally.

**Comment by fabro66** [comment]
Glad to hear that you solved the problem！
