### ISSUE TITLE
How to use our own dataset to get 3D Human Pose Estimation in Video with 2D keypoint json file

### ISSUE THREAD

**Issue by christw16** [fabro66/GAST-Net-3DPoseEstimation#5]
Hi there~
Thank you for sharing this great work!

My question is that how to use our own video to get 3D Human Pose Estimation with your pretrained model.

Thank you

**Comment by fabro66** [comment]
Hi~
Sorry that we have not yet provided the code for 2D keypoint generation. We will release these codes in the feature.

I recommend you to use [HRNet](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch) to generate 2D keypoints and save the keypoints format as like ./data/keypoints/baseball.json. 
Next, follow the ['inference in the wild'](https://github.com/fabro66/GAST-Net-3DPoseEstimation#inference-in-the-wild) step to get your own 3D poses.

**Comment by christw16** [comment]
@fabro66 
OK, I see. Thank you for your answer~

I just use Alphapose to generate 2D keypoints json file for video
And I use that json file resulting in openpose format
It also does not work either.

So that now it only works for HRNet to generate 2D keypoints json file?
Thank you so much~

**Comment by fabro66** [comment]
It may be that the saved keypoints are in a different format.
Could you please post the 2D keypoints generated by Alphapose and let me see which link has bugs.

**Comment by christw16** [comment]
@fabro66 Here are two types of 2D Keypoint json files

1. This is the "openpose" format generating by Alphapose

![image](https://user-images.githubusercontent.com/38533075/89256146-07866080-d656-11ea-9a58-5a16ac38e331.png)

2. This is the "default" format generating by Alphapose

![image](https://user-images.githubusercontent.com/38533075/89256256-487e7500-d656-11ea-8d50-b307eba6603f.png)

**Comment by fabro66** [comment]
Hi~
According to the 2D keypoints file you provided. You can use the following load_json_openpose/alphapose to replace the load_json function in reconstrction.py.
The function only supports load the keypoints estimated from images. But you can extend it to load keypoints from videos.

### openpose
```
def load_json_openpose(kpts_file):
    with open(kpts_file, 'r') as fr:
        img_info = json.load(fr)

    num_person = len(img_info['people'])
    keypoints = np.zeros((num_person, 1, 18, 2), dtype=np.float32)  # (M, T, N, C)
    scores = np.zeros((num_person, 1, 18))  # (M, T, N)

    for i, human_info in enumerate(img_info['people']):
        kpts_scores = np.asarray(human_info['pose_keypoints_2d'], dtype=np.float32)
        kpts_scores = kpts_scores.reshape(18, 3)
        keypoints[num_person, 0] = kpts_scores[:, :2]
        scores[num_person, 0] = kpts_scores[:, 2:]

        return keypoints, scores

```
### Alphapose
```
def load_json_alphapose(kpts_file):
    with open(kpts_file, 'r') as fr:
        img_info = json.load(fr)

    num_person = len(img_info)
    keypoints = np.zeros((num_person, 1, 17, 2), dtype=np.float32)  # (M, T, N, C)
    scores = np.zeros((num_person, 1, 17))  # (M, T, N)

    for i, human_info in enumerate(img_info):
        kpts_scores = np.asarray(human_info['keypoints'], dtype=np.float32)
        kpts_scores = kpts_scores.reshape(17, 3)
        keypoints[num_person, 0] = kpts_scores[:, :2]
        scores[num_person, 0] = kpts_scores[:, 2:]

    return keypoints, scores
```

**Comment by christw16** [comment]
@fabro66  
Thank you very much

Are you going to release the version for how to track and estimate multi-person 3D poses from the video in real-time?
and for  just inputting the video without pre-generating 2D keypoint?

**Comment by fabro66** [comment]
Hi~  Thank you for your interest in our work.
In the future, I will release the newest version with  **improved GAST-Net**  for real-time multi-person 3D poses estimation.
The project will contain human detection and tracking, 2D pose estimation, and 3D pose estimation methods.

**Comment by christw16** [comment]
@fabro66 
Thank you so much~

**Comment by danial880** [comment]
> Hi~ Thank you for your interest in our work.
> In the future, I will release the newest version with **improved GAST-Net** for real-time multi-person 3D poses estimation.
> The project will contain human detection and tracking, 2D pose estimation, and 3D pose estimation methods.

Yes, that's great. How long will it take?

**Comment by fabro66** [comment]
> > Hi~ Thank you for your interest in our work.
> > In the future, I will release the newest version with **improved GAST-Net** for real-time multi-person 3D poses estimation.
> > The project will contain human detection and tracking, 2D pose estimation, and 3D pose estimation methods.
> 
> Yes, that's great. How long will it take?

Hi~  We will provide these codes next month. At the same time, a pre-trained casual model will be provided.

**Comment by rirri93** [comment]
Hi. Sorry, but I have some questions about your load_json function for openpose and openpose-coco conversion in reconstruction.py. 

I modified little things in load_json function for openpose because IMO there were little bugs: 
```
def load_json(kpts_file):
    with open(kpts_file, 'r') as fr:
        img_info = json.load(fr)

    num_person = len(img_info['people'])
    keypoints = np.zeros((num_person, 1, 25, 2), dtype=np.float32)  # HERE I CHANGED 18 TO 25 CAUSE O.P. HAS 25 JOINTS
    scores = np.zeros((num_person, 1, 25))  # SAME HERE

    for i, human_info in enumerate(img_info['people']):
        kpts_scores = np.asarray(human_info['pose_keypoints_2d'], dtype=np.float32)
        kpts_scores = kpts_scores.reshape(25, 3)
        keypoints[i, 0] = kpts_scores[:, :2]
        scores[i, 0] = np.transpose(kpts_scores[:, 2:]) #HERE I TRANSPOSED CAUSE IT WAS NOT WORKING 
    return keypoints, scores
```
This is your code for openpose-coco translation:

```
    elif args.kpts_format == 'openpose':
        # Convert 'Openpose' format to MSCOCO
        order_coco = [i for i in range(17) if i != 1]
        keypoints = keypoints[:order_coco]
        keypoints, valid_frames = coco_h36m(keypoints)
```

Now my question is: what does it mean this line?  `keypoints = keypoints[:order_coco]`
It causes this error: TypeError: slice indices must be integers or None or have an __index__ method
What do you want to do with that line? Maybe you want to select all the rows from 0 to 16 (excluding 1) in keypoints? But why? I don't understand.
